### ISSUE TITLE
Host Checklist

### ISSUE THREAD

**Issue by CFGrote** [mpievolbio-scicomp/2023-04-04-MPIEvolBio#1]
### Before the workshop, the host will
- [x]    Decide on the Software Carpentry, Data Carpentry, or Library Carpentry curriculum that would best serve your learners
- [x]    Fill out the workshop request form
- [x]    Work with The Carpentries Workshop Administration Team to set dates and location for your workshop, unless your workshop is virtual
- [x]        Be sure to account for other events and programs at your site that may affect room availability and participant availability
- [x]        Ensure your location is accessible
- [x]    Recruit helpers to join your workshop. They do not need to be directly connected with The Carpentries. They do need basic knowledge of the tools we teach and enthusiasm to help others learn. We recommend 1 helper for every 8-10 students, not counting the two instructors.
- [x]    Advertise your workshop. The Workshop Administration Team can help by creating an Eventbrite registration page.
- [x]    Decide if you want to charge a workshop fee. Even a small fee can greatly reduce the no-show rate. If the Workshop Administration Team creates an Eventbrite registration page, The Carpentries can collect this fee via Eventbrite and use it to offset your workshop fee.
- [x]    ~Work with The Carpentries Operations Manager to make arrangements to pay the workshop fee (only for Centrally-Organised workshops). This includes being sure vendor forms or other documentation are in place. The actual invoice will be issued after the workshop is complete.~
- [x]    ~Make travel arrangements for visiting instructors (or communicate process to reimburse them for expenses) if the workshop is in person~
- [x]    Get emergency contact information for instructors in case of last minute changes
- [x]    Arrange for required materials and equipment
- [x]    Arrange for coffee, snacks, and/or lunch. We all learn better with fuel!
- [x]    Email learners to remind them of workshop location, timing, pre-workshop survey and software installation requirements
- [x]    Organise a meetup with the instructors the day before the workshop if the workshop is in person, or sooner if the workshop is virtual. While this is not always possible, it is useful for the host and instructors to get to know each other. This can be over coffee, dinner, or anything else that works for your team.
#### During the workshop, the host will
- [x]    Meet the instructors and learners
- [x]    Ensure that the room is set up with all necessary materials and equipment
- [x]    Periodically check in on the class to be sure things are running smoothly
#### After the workshop, the host will
- [x]    Collect workshop attendance
- [x]    Send attendance and any other feedback to The Carpentries Workshop Administration Team
- [x]    Pay the workshop fee (only for Centrally-Organised workshops)
- [x]    Reimburse the instructors

**Comment by CFGrote** [comment]
We'll run a Software Carpentry "Shell, Git, Programming and Plotting with Python" in 3 days

**Comment by CFGrote** [comment]
Dates are set for April 4-6 2023

**Comment by CFGrote** [comment]
Beate (@Coineag) thankfully  agreed to help out at the workshop

**Comment by CFGrote** [comment]
# Curriculum
## Unix Shell: https://swcarpentry.github.io/shell-novice/
## Git: http://swcarpentry.github.io/git-novice
## Plotting and Programming in Python: http://swcarpentry.github.io/python-novice-gapminder/

**Comment by CFGrote** [comment]
Confimed that we can order through Maren being a internal participants only event with > 3 participants.
Asked Paul to sponsor beverages and cookies, will place the order as soon as he replies.
