### ISSUE TITLE
Helpers Checklist

### ISSUE THREAD

**Issue by CFGrote** [mpievolbio-scicomp/2023-04-04-MPIEvolBio#3]
#### Before a workshop, helpers will
- [x]     Introduce themselves to the instructors, letting them know any particular areas of expertise
- [x]     Review the curriculum the instructors will be teaching
- [x]     Review the software installation instructions to be prepared to troubleshoot with learners
- [x]     Make sure the instructors have listed you on the workshop website
    
#### During the workshop, helpers will
- [x]     Help learners with setup problems or anywhere else they get stuck
- [x]     Monitor room for anyone who may need help. Learners may put up a red sticky note or indicate in other ways that they are stuck.
- [x]     Monitor any questions that come up on the collaborative document and answer them or remind the instructor about them during a break.
#### After the workshop, helpers will
- [x]    Send their own feedback to the instructors and the Workshop Administration Team including any configuration problems
- [x]    Consider applying to become a certified Carpentries instructor
